### ISSUE TITLE
Strip Incoming HTML Formatting

### ISSUE THREAD

**Issue by jgosier** [ushahidi/Swiftriver-2011#12]
Simple pie pulls in RSS with markup for some posts, figure out how to strip this.

**Comment by jgosier** [comment]
Temporary fix by commenting out all <span> tags.

**Comment by soe** [comment]
http://simplepie.org/wiki/reference/simplepie/strip_htmltags

**Comment by jgosier** [comment]
Big help Soe, I'll work on this today.
