### ISSUE TITLE
Pressing Enter after typing in a tag gives a 404

### ISSUE THREAD

**Issue by zestyping** [ushahidi/Swiftriver-2011#16]
I entered text into the text field (next to the Tag button).  Instead of clicking "Tag", I pressed Enter.  Result:

The requested URL /main/tagging/feed/ was not found on this server.

**Comment by jgosier** [comment]
User tagging was lost in version 0.2, we'll work on bringing it back for 0.3

**Comment by mrmatthewgriffiths** [comment]
As we have now moved to the new KO3 framework, this functionality is no longer available. Closed

**Comment by jgosier** [comment]
@zesty in other words, you probably want to go ahead and upgrade to the latest release - Batuque
