### ISSUE TITLE
Install error (and fix) on process.php 

### ISSUE THREAD

**Issue by rsweetland** [ushahidi/Swiftriver-2011#19]
Received an error while on process.php on install (error pasted below for reference).

I edited process.php (lines 33-53) which fixed the error. This is posted below (I added isset to the remaining $_POST vars in addition to the first one):

```
public function _index()
{
    if(isset($_POST['basic_db_info'])) {
        $this->_proc_basic_db_info();
    }else if(isset($_POST['advanced_db_info'])){
        $this->_proc_advanced_db_info();
    }else if(isset($_POST['advanced_general_settings'])){
        $this->_proc_general_settings();
    }else if(isset($_POST['basic_general_settings'])){ 
        $this->_proc_basic_general_settings();
    }else if(isset($_POST['advanced_mail_server_settings'])){ 
        $this->_proc_mail_server();
    }else if(isset($_POST['advanced_map_config'])){ 
        $this->_proc_map();
    }else if(isset($_POST['advanced_perm_pre_check'])){ 
        $this->_proc_advanced_pre_perm_check();
    }else if(isset($_POST['basic_perm_pre_check'])){ 
        $this->_proc_basic_pre_perm_check();        
    } else {
        header("Location:.");
    }        
```

Error received for reference:

Notice: Undefined index: advanced_db_info in /Applications/MAMP/htdocs/swift2/swift/installer/process.php on line 37

Notice: Undefined index: advanced_general_settings in /Applications/MAMP/htdocs/swift2/swift/installer/process.php on line 39

Notice: Undefined index: basic_general_settings in /Applications/MAMP/htdocs/swift2/swift/installer/process.php on line 41

Notice: Undefined index: advanced_mail_server_settings in /Applications/MAMP/htdocs/swift2/swift/installer/process.php on line 43

Notice: Undefined index: advanced_map_config in /Applications/MAMP/htdocs/swift2/swift/installer/process.php on line 45

Notice: Undefined index: advanced_perm_pre_check in /Applications/MAMP/htdocs/swift2/swift/installer/process.php on line 47

Warning: Cannot modify header information - headers already sent by (output started at /Applications/MAMP/htdocs/swift2/swift/installer/process.php:37) in /Applications/MAMP/htdocs/swift2/swift/installer/process.php on line 268

**Comment by jgosier** [comment]
Fixed in v.0.2 Batuque
