### ISSUE TITLE
Error Message Submitting News

### ISSUE THREAD

**Issue by rsweetland** [ushahidi/Swiftriver-2011#20]
URL: http://localhost/swift/swift/reports/submit

Error Message Here: 

An error was detected which prevented the loading of this page. If this problem persists, please contact the website administrator.
application/controllers/reports.php [274]:
Undefined index:  incident_ampm
Stack Trace

Reports_Controller->submit(  )
system/core/Kohana.php [272]:
ReflectionMethod->invokeArgs( Reports_Controller Object
(
    [logged_in] => 1
    [auto_render] => 1
    [template] => View Object
        (
            [kohana_filename:protected] => /Applications/MAMP/htdocs/swift/swift/application/views/layout.php
            [kohana_filetype:protected] => .php
            [kohana_local_data:protected] => Array
                (
                    [header] => View Object
                        (
                            [kohana_filename:protected] => /Applications/MAMP/htdocs/swift/swift/application/views/header.php
                            [kohana_filetype:protected] => .php
                            [kohana_local_data:protected] => Array
                                (
                                    [site_name] => Reilly's Test Swift Insatll
                                    [site_name_style] =>  style="font-size:21px;"
                                    [site_tagline] => Developing cool things with swift
                                    [api_url] => <script src="http://maps.google.com/maps?file=api&v=2&key=ABQIAAAAjsEM5UsvCPCIHp80spK1kBQKW7L4j6gYznY0oMkScAbKwifzxxRhJ3SP_ijydkmJpN3jX8kn5r5fEQ" type="text/javascript"></script>
                                    [site_contact_page] => 1
                                    [site_help_page] => 1
                                    [pages] => ORM_Iterator Object
                                        (
                                            [class_name:protected] => Page_Model
                                            [primary_key:protected] => id
                                            [primary_val:protected] => name
                                            [result:protected] => Mysql_Result Object
                                                (
                                                    [fetch_type:protected] => mysql_fetch_object
                                                    [return_type:protected] => stdClass
                                                    [result:protected] => Resource id #64
                                                    [insert_id:protected] => 
                                                    [sql:protected] => SELECT `page`.*
FROM `page`
WHERE `page_active` = '1'
ORDER BY `page`.`id` ASC
                                                    [current_row:protected] => 0
                                                    [total_rows:protected] => 2
                                                )

```
                                    )

                                [site_style] => default
                                [allow_feed] => 1
                                [map_enabled] => 
                                [validator_enabled] => 1
                                [datepicker_enabled] => 
                                [photoslider_enabled] => 
                                [videoslider_enabled] => 
                                [protochart_enabled] => 
                                [main_page] => 
                                [this_page] => reports_submit
                                [locales_array] => 
                                [l] => en_US
                            )

                    )

                [footer] => View Object
                    (
                        [kohana_filename:protected] => /Applications/MAMP/htdocs/swift/swift/application/views/footer.php
                        [kohana_filetype:protected] => .php
                        [kohana_local_data:protected] => Array
                            (
                                [google_analytics] => 
                                [tracker_url] => http://tracker.ushahidi.com/track.php?url=null&lang=en_US&version=0.0.9
                                [ushahidi_stats] => SimpleXMLElement Object
                                    (
                                        [0] => <!-- Piwik -->
    <script type="text/javascript">
    var pkBaseURL = (("https:" == document.location.protocol) ? "https://tracker.ushahidi.com/piwik/" : "http://tracker.ushahidi.com/piwik/");
    document.write(unescape("%3Cscript src='" + pkBaseURL + "piwik.js' type='text/javascript'%3E%3C/script%3E"));

    </script><script type="text/javascript">
    try {
      var piwikTracker = Piwik.getTracker(pkBaseURL + "piwik.php", 1406);
      piwikTracker.trackPageView();
      piwikTracker.enableLinkTracking();
    } catch( err ) {}
    </script><noscript><p><img src="http://tracker.ushahidi.com/piwik/piwik.php?idsite=1406" style="border:0" alt=""/></p></noscript>

    <!-- End Piwik Tag -->

                                    )

                            )

                    )

                [content] => View Object
                    (
                        [kohana_filename:protected] => /Applications/MAMP/htdocs/swift/swift/application/views/reports_submit.php
                        [kohana_filetype:protected] => .php
                        [kohana_local_data:protected] => Array
                            (
                            )

                    )

            )

    )

[cache:protected] => Cache Object
    (
        [config:protected] => Array
            (
                [driver] => file
                [params] => /Applications/MAMP/htdocs/swift/swift/application/cache
                [lifetime] => 1800
                [requests] => 1000
            )

        [driver:protected] => Cache_File_Driver Object
            (
                [directory:protected] => /Applications/MAMP/htdocs/swift/swift/application/cache/
            )

    )

[session:protected] => Session Object
    (
        [input:protected] => Input Object
            (
                [use_xss_clean:protected] => 1
                [magic_quotes_gpc:protected] => 1
                [ip_address] => 
            )

    )

[uri] => URI Object
    (
    )

[input] => Input Object
    (
        [use_xss_clean:protected] => 1
        [magic_quotes_gpc:protected] => 1
        [ip_address] => 
    )
```

)
 )
Kohana::instance(  )
system/core/Event.php [209]:
call_user_func( Array
(
    [0] => Kohana
    [1] => instance
)
 )
system/core/Bootstrap.php [60]:
Event::run( system.execute )
index.php [131]:
require( system/core/Bootstrap.php )

**Comment by jgosier** [comment]
All taken care of in v.0.2.0 Batuque
