### ISSUE TITLE
/atom/feed doesn't retrieve the Atom feed

### ISSUE THREAD

**Issue by zestyping** [ushahidi/Swiftriver-2011#21]
Instead, I get an Ushahidi error page:

Page Not Found!
Sorry, the page you are trying to view is not here.
Did you follow a link from somewhere else on our site?
If you reached this page from another part of our site, please contact us so that we can correct our mistake.

Did you follow a link from another site? 
Links from other sites can sometimes be outdated or misspelled. Tell us where you came from and we can try to contact the other site in order to fix the problem.

Did you type the URL? 
You may have typed the address (URL) incorrectly. Check to make sure you've got the exact right spelling, capitalization, etc.

server url /swift/index.php/feed/atom

**Comment by jgosier** [comment]
Fixed with SiPS modules in v.0.2 Batuque
