### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by ernestoalegre** [ushahidi/Swiftriver-2011#34]
My browser says:

"var data = {"checks":
Fatal error: Call to undefined function: json_encode() in /home/my_account/public_html/swift/installer/step-php-checks.php on line 55"

What can I do?

**Comment by jgosier** [comment]
Which version are you using?  Rumba or Apala?  Or did you download from the repo?

**Comment by ernestoalegre** [comment]
Hi appfrica, I'm using Version 0.1.0 Apala

**Comment by jgosier** [comment]
Ahh, that version has a lot of issues.  In hindsight we probably shouldn't have shipped it.  Two options.  1) the next version 0.2.0 comes out in one week.  you could wait until then.  2) download the nightly build from the repo.  It's still buggy but far-more stable than Apala.

**Comment by ernestoalegre** [comment]
Thank you for your assistance...
I will wait 1 week!

**Comment by jgosier** [comment]
It's out! http://swift.ushahidi.com/dl/
