### ISSUE TITLE
Database table not created

### ISSUE THREAD

**Issue by soe** [ushahidi/Swiftriver-2011#35]
My scenario was that the database for Swift is not created on my own but the installation process gives me the impression that it could create the database on its own.

However, when I create an empty database then trying out the Swift instance. It creates a table for api in the database and the instance starts to function.

**Comment by jgosier** [comment]
Please let us know which version you're using.  If you aren't sure, pointing us to the location where you downloaded should let us know.

**Comment by soe** [comment]
Oh sorry, for not being specific. I thought it was labeled.

I am using 0.1.0 Apala.

**Comment by jgosier** [comment]
this is fixed in 0.2 Batuque
