### ISSUE TITLE
auto-trust option for sources

### ISSUE THREAD

**Issue by jgosier** [ushahidi/Swiftriver-2011#36]
users should be able to explicitly declare trust for a source, giving that source an automatic score of 100%

**Comment by soe** [comment]
how would this work? where do the users declare sources?

**Comment by jgosier** [comment]
One the side pannel under channels.  The channel is the delivery method (Twitter Search, SMS, Twitter, Email etc) the source is the feed itself.  Items are individual content items coming from those channels.   There used to be a little box next to each that allowed the user to explicitly declare it as trusted, we need to bring it back.
