### ISSUE TITLE
404 Errors after install

### ISSUE THREAD

**Issue by jdarnell** [ushahidi/Swiftriver-2011#40]
I have installed the nightly build (June 3rd 2010) of Batuque on an Ubuntu 10.04 server.  I made sure the the system requirements and right packages are met.  I also made sure the database existed and was writable by the correct user with the right password. When I go to the root directory (example http://localhost/Swiftriver) I am able to see the page.  However if I click on "Themes", "Turbines", "Irrelevant" nothing happens.  If I click on links like "Accurate", "Inaccurate", "Cross-talk" it goes to a 404 error page.  Am I doing something wrong?

**Comment by mrmatthewgriffiths** [comment]
Hi JDarnell, I think you will find that something has gone wrong with the writing of environment specific data to either the .htaccess or the bootstrap.php file. If you installed the app to run in folder "swiftriver" (giving a web address of http://localhost/Swiftriver) then the .htaccess file should contain a line that reads "RewriteBase /Swiftriver/web/" and the bootstrap.php file should contain a line that reads "'base_url' => '/Swiftriver/web/'". If they don't can you try to edit them manually.

**Comment by jdarnell** [comment]
mrmathewgriffiths,  Thank you for the response, I did confirm both lines were accurate in the .htaccess file and bootstrap.php file.  However, I am still having the same issue...

**Comment by mrmatthewgriffiths** [comment]
Hi JDarnell, If both lines in the .htaccess fie and the bootstrap file are fine then at least that means the installer is working correctly :-) Can you see if you have mod_rewrite installed and enabled on your server (you can use a info.php file for this). Mod_rewrite is a pre-req of the Kohana framework but out installer dose not currently look for it. Matt

**Comment by jdarnell** [comment]
Thanks for the help but info.php shows that "mod_rewrite" is a loaded module. hm...

**Comment by mrmatthewgriffiths** [comment]
Hi Jake, Sorry to keep bouncing you around like this. I think the next best step is to try and run a clean copy of the Kohana V3 framework. If you go here http://kohanaframework.org/guide/about.install and follow the setup instructions you will get an Environment Test page at the end, this should all be green. Have a go and then let me know.

**Comment by jdarnell** [comment]
Hi again Matthew, thanks for your continued help.  I followed the instructions and the test showed that everything passed. I renamed the install.php file and even got the "hello, world!" text that I was supposed to get.  Do you think the .htaccess file is re-writing the paths wrong? I wonder what could be doing this.
