### ISSUE TITLE
Swiftriver Installation probelm on WAMP

### ISSUE THREAD

**Issue by prateeksingh** [ushahidi/Swiftriver-2011#41]
Hii

We are setting up ushahidi for mapping water crisis in india. So for the same reason we are installing Swiftriver also. Our webserver is having older version of PhP, by the time someone updates to PHP5.3 I thought I will use SwiftRiver on my local machine. 
I installed it, it looks like proper installation but two issues:

1.) I am not getting login page neither any option/link to log in as administrator
2.) There are no tables created in database

Please help me with these issues. 

I didn't receive any error message while installing, it was swift ;) and smooth. I am using Firefox3.6, WAMP5 and Windows Vista Home Premium. 

Regards
Prateek

**Comment by mrmatthewgriffiths** [comment]
Hi Prateek,

Thanks for getting in touch with us at Swiftriver and I'm really glad you are thinking of piloting our software in your situation!

So to address your points in turn:
1. In the current alpha release, there are no user roles. We at Swiftriver realise this may limit the ability of the current software release to be deployed but hope that in your case it will not. All configuration can be done using the links marked 'Turbines' and 'Sources' that appear in the grey bar at the very top of the screen (if you can not see these on your current install, try getting the latest code from our repo).
2. The current alpha release ships with a dynamic data base creation layer, as such, nothing will appear in the data base until you start adding sources.

Something of note that is not in our technical docs is that all actions taken by the Swiftriver application are logged in the file [your-install]/core/Cache/log.log

Let me know how you get on, Matt

**Comment by prateeksingh** [comment]
Hi Matt

I really appreciate your prompt and very clean reply. 

I downloaded the latest code from "github" I installed it, only error which occurred was, there was no cache directory in core directory so, I manually created there. It installed properly. I can see "Sources" link on top but when i click on it nothing happens. Turbines and Theme links are working fine.

I checked log file also there is a pattern of logs in each second, i am pasting it here:

Jun 20 12:54:02     [info] Core::ServiceAPI::ChannelProcessingJobs::ListAvailableChannelTypes::RunWorkflow [Method invoked]
Jun 20 12:54:02     [debug] Core::ServiceAPI::ChannelProcessingJobs::ListAvailableChannelTypes::RunWorkflow [START: Constructing SiSPS]
Jun 20 12:54:02     [debug] Core::ServiceAPI::ChannelProcessingJobs::ListAvailableChannelTypes::RunWorkflow [END: Constructing SiSPS]
Jun 20 12:54:02     [debug] Core::ServiceAPI::ChannelProcessingJobs::ListAvailableChannelTypes::RunWorkflow [START: Getting the list of available parsers]
Jun 20 12:54:02     [debug] Core::Modules::SiSPS::SwiftriverSourceParsingService::ListAvailableChannels [Method invoked]
Jun 20 12:54:02     [debug] Core::Modules::SiSPS::SwiftriverSourceParsingService::ListAvailableChannels [START: Getting All Parsers from the ParserFactory]
Jun 20 12:54:02     [debug] Core::Modules::SiSPS::ParserFactory::ReturnAllAvailableParsers [Method invoked]
Jun 20 12:54:02     [debug] Core::Modules::SiSPS::ParserFactory::ReturnAllAvailableParsers [START: Directory Itteration]
Jun 20 12:54:02     [debug] Core::Modules::SiSPS::ParserFactory::ReturnAllAvailableParsers [Adding type \Swiftriver\Core\Modules\SiSPS\Parsers\FeedsParser]
Jun 20 12:54:02     [debug] Core::Modules::SiSPS::ParserFactory::ReturnAllAvailableParsers [Adding type \Swiftriver\Core\Modules\SiSPS\Parsers\TwitterParser]
Jun 20 12:54:02     [debug] Core::Modules::SiSPS::ParserFactory::ReturnAllAvailableParsers [END: Directory Itteration]
Jun 20 12:54:02     [debug] Core::Modules::SiSPS::SwiftriverSourceParsingService::ListAvailableChannels [END: Getting All Parsers from the ParserFactory]
Jun 20 12:54:02     [debug] Core::Modules::SiSPS::SwiftriverSourceParsingService::ListAvailableChannels [Method finished]
Jun 20 12:54:02     [debug] Core::ServiceAPI::ChannelProcessingJobs::ListAvailableChannelTypes::RunWorkflow [END: Getting the list of available parsers]
Jun 20 12:54:02     [debug] Core::ServiceAPI::ChannelProcessingJobs::ListAvailableChannelTypes::RunWorkflow [START: Parsing to return JSON]
Jun 20 12:54:02     [debug] Core::ServiceAPI::ChannelProcessingJobs::ListAvailableChannelTypes::RunWorkflow [END: Parsing to return JSON]
Jun 20 12:54:02     [info] Core::ServiceAPI::ChannelProcessingJobs::ListAvailableChannelTypes::RunWorkflow [Method finished]
Jun 20 12:54:02     [info] Core::Workflows::ChannelServices::GetAllChannels::RunWorkflow [Method invoked]
Jun 20 12:54:02     [debug] Core::Workflows::ChannelServices::GetAllChannels::RunWorkflow [START: Constructing Repository]
Jun 20 12:54:02     [debug] Core::Workflows::ChannelServices::GetAllChannels::RunWorkflow [END: Constructing Repository]
Jun 20 12:54:02     [debug] Core::Workflows::ChannelServices::GetAllChannels::RunWorkflow [START: Listing all Channels]
Jun 20 12:54:02     [debug] Core::DAL::Repositories::ChannelRepository::ListAllChannels [Method invoked]
Jun 20 12:54:02     [debug] Core::Modules::DataContext::MySQL_V1::DataContext::ListAllChannels [Method invoked]
Jun 20 12:54:02     [debug] Core::Modules::DataContext::MySQL_V1::DataContext::ListAllChannels [START: Querying the data store]
Jun 20 12:54:02     [debug] Core::Workflows::ChannelServices::GetAllChannels::RunWorkflow [An exception was thrown]
Jun 20 12:54:02     [error] Core::Workflows::ChannelServices::GetAllChannels::RunWorkflow [SQLSTATE[42S02]: Base table or view not found: 1146 Table 'swiftriver.channel' doesn't exist]
Jun 20 12:54:02     [info] Core::Workflows::ChannelServices::GetAllChannels::RunWorkflow [Method finished]

These lines are repeating again and again, and all the time I am getting this error (the second last line "Core::Workflows::ChannelServices::GetAllChannels::RunWorkflow [SQLSTATE[42S02]: Base table or view not found: 1146 Table 'swiftriver.channel' doesn't exist". I am sorry Matt to paste all the lines...I think it can save some time :)

How should I go ahead, please help me here.

Regards
Prateek

**Comment by mrmatthewgriffiths** [comment]
Hi Prateek,

Thanks for sending me the log exerts. It really helped me to track down the issue that has been causing you these problems for you. I believe that the issue is a code bug but before I ask you to download the source code again (sorry about that), I would like you to examine the configuration file found in:

[your-root]/core/Modules/DataContext/MySQL_V1/Configuration.xml

In this file, you should find the address, user-name and password that are used for all core->db communications.

If these details are not correct, can you manually adjust them and then let me know how that works out.

In addition, I have implemented a code fix that should prevent the errors from happening again. If your db access details are ok, please download the latest source code and try again with the new code fix. 

Sorry for messing you around and thanks again for sticking with Swiftriver.

Matt

**Comment by prateeksingh** [comment]
Hi Matt

I am sorry for delayed response, I was just busy with some household stuff.

I installed the latest code (downloaded again) and it worked on Localserver very well. I transferred same code to webserve and tried to install. The installation is error free, no problem at all. But SwiftRiver main page is not opening, i am getting this error:

"/public_html/swiftdata/web/.htaccess: RewriteRule: cannot compile regular expression '^(?:application|modules|system)\b'\n"

I have set permission for ".htaccess" as 755 still it is not working. Can you please help me with, what permission should i set for ".htaccess" file. I think this error is primarily because of wrong permission to file. I checked regular expression they looks fine. :)

regards
prateek

**Comment by JonnyPhillips** [comment]
Hi guys,

Hope you are well - I just wondered if anyone resolved Prateek's final post (June 23rd)? I'm having the same problem - Installation runs fine but before I can login or see any interface I get a 500 - Internal Server Error. The error log reports:

[Mon Dec 27 09:22:19 2010] [alert] [client 82.27.102.73] /home/nigeria0/public_html/swiftly/web/.htaccess: RewriteRule: cannot compile regular expression '^(?:application|modules|system)\b'\n

I think I have the all the prerequisites - Apache 1.3.42, Php 5.3.0, pear etc. Deeply grateful for any advice you can provide.

Many thanks,

Jonathan
