### ISSUE TITLE
can't login in to SwiftRiver v0.5.0

### ISSUE THREAD

**Issue by macsmith** [ushahidi/Swiftriver-2011#43]
I've just installed SwiftRiver v0.5.0 on my server but can't log in.  I'm at the http://myserver/swift/web/ page and the Log In button does nothing.

Help!

Ian

**Comment by mrmatthewgriffiths** [comment]
Hello Ian,

If you have completed the install and everything was ok then this is good. If you press the 'login' button and nothing happens then perhaps you could try running a browser plugin like firebug to see if the AJAX get request that is fired from that button click is working.

It may also be worth checking that the data base connection values in the below file have been set correctly:

[root]/web/modules/riverid/riveridconfig.php

Matt

**Comment by macsmith** [comment]
thanks for the reply.  It installed without error and the config file looks ok, though it is actually at [root]/web/modules/riverid/classes/riveridconfig.php.

I have firebug but haven't used it much and am not sure how to make the check you suggest.

Thanks

Ian

**Comment by mrmatthewgriffiths** [comment]
Hi Ian,

I can of cause give you a [very] quick guide to fire bug ... if you have the plugin installed then hit the home page of rhte swiftriver app with firbug open -> in the console tab (make sure its enabled by hitting the small arrow next to the word 'Console' and selecting 'enable') -> you should see all the AJAX requests being made by the application -> press the login button -> scroll to the bottom of the lists of request in firebug -> look for a request in red -> click on the request in red -> examine the error and post some info here.

Hope this helps,

Matt

**Comment by macsmith** [comment]
thanks for that and what a useful tool!  Just loading the page generated a 404 error:

The requested URL /swift/web/api/contentselection/get/accurate/0/100/null/null/null/20/0/null was not found on this server.</p>

Apache/2.2.14 (Ubuntu) Server at 192.168.2.66 Port 80

Looks like a configuration problem somewhere.  The install was clean.

Thanks

Ian

**Comment by mrmatthewgriffiths** [comment]
Hi Ian,

It defo is a great tool and I use it all the time!

So, first thing is first: does the url above look right ... I mean did you install the app in a 'swift' folder in the root of your web server?

Matt

**Comment by macsmith** [comment]
yes, the url is correct and the swift home page is: http://192.168.2.66/swift/web/

**Comment by mrmatthewgriffiths** [comment]
Hi Ian,

Ok then this seems like a url mapping issue. Can you take the URL that you pasted here and put it directly in the browser (adding the correct IP of cause) and let me know the error that comes back.

Matt

**Comment by macsmith** [comment]
sorry, I'm not sure which url you mean.  The first one I pasted has nulls in it and the 2nd one is the swift home page with the log in button.

Thanks

Ian

**Comment by mrmatthewgriffiths** [comment]
Hi Ian,

Apologies for being unclear:

Please paste this into your browser and tell me what happens

http://192.168.2.66/swift/web/api/contentselection/get/accurate/0/100/null/null/null/20/0/null

Matt

**Comment by macsmith** [comment]
it generates a 404 error.

thanks

Ian

**Comment by mrmatthewgriffiths** [comment]
Hi Ian,

can you please paste the content of the following file into this issue tracker:

[root]/web/.htaccess

Matt

**Comment by macsmith** [comment]
I don't have a .htaccess file in [root] and I don't have a [root]/web directory (if that's what you meant).  There is an htaccess.txt file in [root] but presumably this is not invoked(?).

root@FPserver:/var/www# ls -a
.                       CREDITS.php   joomla        plugins
..                      htaccess.txt  language      robots.txt
administrator           images        libraries     swift
cache                   includes      LICENSE.php   templates
CHANGELOG.php           index2.php    LICENSES.php  tmp
components              index.php     logs          xmlrpc
configuration.php       ins           media
configuration.php-dist  INSTALL.php   modules
COPYRIGHT.php           ioncube       php.ini

**Comment by mrmatthewgriffiths** [comment]
Hi Ian,

by [root] I mean where you installed swiftriver to. In your case, this would be /var/www/swift (I think) ... meaning that there should be a .htaccess file @ /var/www/swift/web/.htaccess

Matt

**Comment by macsmith** [comment]
sorry, my stupidity!

root@FPserver:/var/www/swift/web# more .htaccess 

# Turn on URL rewriting

RewriteEngine On

# Installation directory

RewriteBase /swift/web/ 

# Protect hidden files from being viewed

<Files .*>
        Order Deny,Allow
        Deny From All
</Files>

# Protect application and system files from being viewed

RewriteRule ^(?:application|modules|system)\b index.php/$0 [L]

# Allow any files or directories that exist to be displayed directly

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

# Rewrite all other URLs to index.php/URL

RewriteRule .\* index.php/$0 [PT]

**Comment by mrmatthewgriffiths** [comment]
No problems,

So the thing I was looking for is here and is ok (basically the line that starts RewriteBase).

So this leads me to think that some of the prerequisite for the Kohana framework (this is the PHP framework that the web application part of swiftriver is built on) are not there.

Can you create a php info file (http://docs.simplemachines.org/index.php?topic=479.0) upload it and then paste the result here.

Matt

**Comment by macsmith** [comment]
done that but the output is huge.  You do want me to paste it here?

**Comment by macsmith** [comment]
I also don't have kohana installed, even more stupid me!  But should the Swift installer have picked that up?

Thanks

Ian

**Comment by mrmatthewgriffiths** [comment]
Hi Ian,

Dont worry about the Kohana thing, we have packaged most of it up with the swiftriver release so you should not have to worry.

When you hit the phpinfo page can you search for mod_rewrite and let me know if this module is enabled or not.

Matt

**Comment by macsmith** [comment]
the only item on the php info output page with rewrite is:

url_rewriter.tags   a=href,area=href,frame=src,input=src,form=fakeentry a=href,area=href,frame=src,input=src,form=fakeentry

**Comment by mrmatthewgriffiths** [comment]
Hi Ian,

Then this means that you dont have the apache module mod_rewrite installed and activated. I'm afraid that you wont be able to run swiftriver without it.

Can you have a google for installing and activating it on your platform and then try to do just that. Then let me know how you get on.

Matt

**Comment by macsmith** [comment]
ok.  After lunch...

Thanks

Ian

**Comment by mrmatthewgriffiths** [comment]
Hi Ian,

I will be away from my main PC for a little while myself, if you would like to get instant feedback then please email me on    -  mg [ a t ] swiftly [ d o t ] org

Matt

**Comment by macsmith** [comment]
ok, got mod_rewrite loaded, as verified by phpinfo().  No change to swift login :-(

Cheers

Ian

**Comment by mrmatthewgriffiths** [comment]
Hi Ian, 

would you mind email me directly at   mg [ a t ] swiftly [ d o t ] org  ?

Many thanks

**Comment by azstumbler** [comment]
OK I have the same problem. same version of swift river, ,htacess is good, mod_rewrite installed, got the same url when using firebug and still not able to log in. And running it on Fedora 14 64 bits

**Comment by agemaia** [comment]
Did anybody solve this issue? I've just installed Swiftriver in WAMP Windows XP with no problems but the login button does nothing.

Any clues? Thanks a lot.

**Comment by alefel** [comment]
Hey,

I found a solution for that problem (using Ubuntu):
First ensure that mod_rewrite is activated like mentioned above
Second: Edit /etc/apache2/sites-available/default and ensure that ./htaccess is read by changing "AllowOverride None" to "AllowOverride All" in the entry for your directory in which you installed swiftriver. Mind that the options in the Directory-directive are inherited. E.g. in my case I changed

Directory /var/www/
    Options Indexes FollowSymLinks MultiViews
    AllowOverride None
    Order allow,deny
    allow from all
/Directory

to

Directory /var/www/
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Order allow,deny
    allow from all
/Directory

Hope, it helps.

Cheers,
Alex

**Comment by mkhines** [comment]
Hi Alex,

Unfortunately, even with those edits to my httpd configuration file for Apache, I am still getting an error in Firebug console, under response this is the message -

404 Not Found

The requested URL /swiftriver/web/config/loginandregister/login was not found on this server.

Which points out a pathway that does not exist.  so a 404 message is pretty accurate.  There is no /config directory in the installed package.  Can someone help with a fix for this?  It seems like some people have the fix, and others do not somehow?  The installation goes through successfully, but for whatever reason, this path error continues to exist, but only evident when clicking on the Log in button.  How can this be solved locally?   

Thank you,
Megan

**Comment by alefel** [comment]
That the directory not exist, is ok. The .htaccess in the web-directory switches on the rewrite engine and most important is the last line of the .htaccess file stating that all paths, filenames etc (".*" means absolutely everything, it's a common regular expression) are rewritten (or internally transformed by apache). With the rewrite engine switched on, the paths and files do not have to exist.

I found out this issue, after purposefully adding mistakes into the .htaccess-file. E.g. I wrote
RewriteEngine Odjsfhsdkjhfdsjln

Usually apache responses to these errors (or even the tiniest mispellings) with a big and scary internal server error (500). Try it out and check, if the .htaccess is even executed. If not then you will not get an internal server error and hence it is a configuration issue of apache.

Btw, after changing the configuration file as stated in my post above, you did restart apache, right? (/etc/init.d/apache2 restart) and you also checked, if your are working on the entry with the right directory.

Alex

**Comment by lucianosb** [comment]
The problem still persists. I'm using XAMPP for windows latest release and the login still doesn't work for me either.

XAMPP already has the settings described by @alefel and besides that I also get the same error as @mkhines did when clicking the button.

**Comment by mkhines** [comment]
Also, just to follow up, same issue is encountered when I set up an environment from scratch versus using XAMPP.  I have tried both methods, and neither gets beyond the login problem.  

Thanks,
Megan

**Comment by lucianosb** [comment]
New clue on this issue:

It seems to be a problem on the way controllers are being called or referenced. The path "config/loginandregister/login", which me and Megan reported as 404 does exist and it can be found at the /application/classes/controller/ directory. 

To make things clear at the url: config is a directory, loginandregister is a controller (loginandregister.php file) and login is an action of the controller. As is the register action. Both only call their respective views.

I believe Kohana is trying to find config as a controller not as a directory. Not sure about that, I'll dig the Kohana docs to find something about it.

Another issue confirm my suspicions. When accessing "swift/web/contentlist/get/accurate", which is the link at the Accurate Content tab, I'm also getting the 404 error. And the url also exists for it stands for the contentlist.php controller at the /application/classes/controller/ directory, where get is action and accurate is a parameter.

I hope I'm close to find it all out.

**Comment by lucianosb** [comment]
As the routing rules seem to be correct I went back to the .htaccess file to look for a solution. I replaced "RewriteBase /web/" for "RewriteBase /" and something happened.

The button when clicked calls the correct URL and brings the Shadowbox now. But instead of pulling the proper view for logging in, it pulled my /xampp directory. Maybe installing swift on the root might solve this. I'll update this later.

**Comment by mkhines** [comment]
Hi Lucianosb, thanks for your perseverance.  Unfortunately I have tried to install at root, but without your RewriteBase modification..  I'll try that too.  -Megan

**Comment by theH0Tcarl** [comment]
When I installed Sweeper with it's own database, I couldn't logon with the error that my credentials were wrong.

When I installed Sweeper using the DB that I use for the ushahidi install, the login button just didn't seem to work (instead of throwing an invalid credentials error).

I ended up fixing this during another install of sweeper. I installed sweeper to its own database for this attempt. After entering the DB information during setup and before it prompted me for an admin password, I checked the DB and several tables had been created. I noticed there was no 'users' table like the ushahidi install. 

While the install was still 'paused', I ran the following SQL in the database I had created (I called it sweeper):
CREATE TABLE IF NOT EXISTS users ( username VARCHAR(2000), password VARCHAR(2000), role VARCHAR(2000) )

This is taken directly from [sweeperBase]\web\modules\riverid\classes\riveridconfig.php in the variable $createsql except I omitted 'TYPE=innodb'. When I first ran the query with 'TYPE=innodb' on the end, MySQL threw an error.

Anyway, I now had the users table in the database. I continued with the install and entered an admin password. After the install was complete I was able to log on. I queried the users table and there was one record for user admin.

Hope this helps.

**Comment by lucianosb** [comment]
I believe you got that right! My whole database is empty!!!

The MySQL_v1 files were correctly written on, so my writings permissions are ok. My database credentials are also correct. I'll try to run all tables queries manually.

**Comment by josefd8** [comment]
Hello,

Same issue here, Installing Switfriver with XAMPP but this time on windows vista. When the Login button is pressed........Nothing happens, and I haven't been able to go any further because of this. I tried the advises on these threat but nothing seems to work.

Please, anyone, have the solution for this? I really need it working :(

**Comment by mrmatthewgriffiths** [comment]
Hi Everyone, The Swiftriver team recently pushed out a new version of the Sweeper application, this new version has quite a few new installer tweaks (that should make the process of getting up and running a whole lot easier) and it also has a lovely new UI. Check out this blog post for details: http://blog.swiftly.org/post/3580160431/sweeper-v0-3-0-released

**Comment by josefd8** [comment]
Hello,

I'm testing SwiftRiver on my XAMPP server using windows vista. 

The installation process went just fine. After fixing the login  button problem (which did nothing when pressed) I found that when I type my username and password, Switfriver replied with "wrong credentials". I checked the RiverIdConfig on \web\modules\riverid\classes and all the settings were fine. I went to the DB and there were not a 'users' table created.

I created one myself with the query described on the RiverIdConfig file, and set an user and password fields but still nothing, It keeps saying "wrong credentials"

Any help would be appreciated

**Comment by dexteronomy** [comment]
I have the same issue as josefd8.  Fresh install, seemed fine, but cannot login and no user table in db.

**Comment by josefd8** [comment]
Hi dexterinteractive,

I finally solved it. You have to FIRST create the db for the application, let’s say, the "SwitfRiver" db, and then insert into this the 'users' table. Once this steps are completed, you can proceed with a fresh install of SwitfRiver.

After the install is done, you will see in the 'users' table that a new user was added, with name 'admin', and a bunch of random characters on password (that’s the password you submit during the installation, but encrypted)

Hope this helps

**Comment by arturolp** [comment]
josefd8 was right, creating the database solves the problem... Here is the actual SQL to add:

CREATE TABLE IF NOT EXISTS users ( username VARCHAR(2000), password VARCHAR(2000), role VARCHAR(2000) ) TYPE=innodb

This is line 9 in C:\xampp\htdocs\sweeper\web\modules\riverid\classes\riveridconfig file

**Comment by arturolp** [comment]
The last comment will solve the issue with the login problem, but once you're inside, nothing seems to work...
