### ISSUE TITLE
Installer blank page

### ISSUE THREAD

**Issue by christiankakesa** [ushahidi/Swiftriver-2011#44]
I just retrieve the project with git but some php synthaxe errors appear :
Warning: Unexpected character in input: '\' (ASCII=92) state=1 in .../installer/steps/FileRewriting.php on line 90
Warning: Unexpected character in input: '\' (ASCII=92) state=1 in .../installer/steps/UserCreation.php on line 59
Warning: Unexpected character in input: '\' (ASCII=92) state=1 in .../installer/steps/DBSetup.php on line 56
Warning: Unexpected character in input: '\' (ASCII=92) state=1 in .../installer/steps/DBSetup.php on line 56
Parse error: syntax error, unexpected T_STRING in .../installer/steps/DBSetup.php on line 56

**Comment by christiankakesa** [comment]
Oups, I run run php 5.2.x. I'll upgrade. No bug here.

**Comment by jgosier** [comment]
Thanks for stating the Fix, let us know if you have any more trouble

**Comment by christiankakesa** [comment]
With php 5.3.2 and pear Log, install is OK.
