### ISSUE TITLE
SMS feed

### ISSUE THREAD

**Issue by Pineapple-zz** [ushahidi/Swiftriver-2011#45]
Hi

How is it possible to setup an SMS feed in the latest version of Swift (0.50)? It appears to only support Blogs, News, You Tube and Twitter. Am I missing something?

regards and thanks

Andrew Walters
Australia

**Comment by mrmatthewgriffiths** [comment]
Hi Andrew,

There is no direct support for any of the SMS Gateway API's that ship with this version of Swiftriver, we do of cause have them on our road map!

Do you have a specific gateway in mind?

Matt

**Comment by Pineapple-zz** [comment]
Ah, that makes sense then. I was trying both SlingshotSMS and Frontline - obviously without any success.

regards

Andrew

**Comment by mrmatthewgriffiths** [comment]
Hi Andrew,

While the SMS gateway parsers are still in the pipeline, you can leverage FrontlineSMS's Forward To Email option and then read these into Swiftriver using the Email Parser, this parser is still in development but I have an alpha release I can let you have if you're interested???

Matt

**Comment by Pineapple-zz** [comment]
An excellent suggestion! I would be very interested; I've been going around in circles with this for days and couldn't find a resolution. I understand that it's got it's risks but it's better than nothing and I might be able to give you some testing feedback.

thanks again,

Andrew

**Comment by mrmatthewgriffiths** [comment]
If anyone is interested in an alpha release of the Email parser that would allow the kind of FrontlineSMS integration discussed here please send an email to mg@swiftly.org and I will forward you the parser and some brief installation instructions.

Matt

**Comment by jgosier** [comment]
@Pineapple we should have a better solution for FLSMS available in mid-October

**Comment by Pineapple-zz** [comment]
Look forward to it.
