### ISSUE TITLE
Table channel doesn't exists

### ISSUE THREAD

**Issue by christiankakesa** [ushahidi/Swiftriver-2011#46]
After installing Swiftriver, Login is Ok.
But I can't add Content Sources I have this error : 
{"message":"An exception was thrown: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'testkakesa.channel' doesn't exist"}

In fact after install I have only "users" table created. 
I manually create the tables who was mentioned in source code but I dind't found the channel table structure or DDL.

Note that First time I try to create a source content feed, the javascript:DeleteChannel('') parameter is empty. I think that's because of no chanel table ?

Can you help ?

**Comment by christiankakesa** [comment]
A tips before having official fix : 
create the channel table with this DDL : 

CREATE TABLE IF NOT EXISTS `channel` (
`id` int(11) NOT NULL AUTO_INCREMENT,
`textId` varchar(32) DEFAULT NULL,
PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

Now adding content source works and the needed columns in channel table are automatically added by the framework...

**Comment by mrmatthewgriffiths** [comment]
Hi,

In the beta release all the sql tables are created dynamically. As and when you need to use them. 

In short, if you haven't added any channels yet then there wont be a channels table in the DB.

The reason the users table is there is that during set up you enter the password for the admin account and it gets stored there.

You should be able to just "use" your instance and the DB will be created on the fly as and when the tables are needed.

Please let me know if this is not the case.

Matt

**Comment by christiankakesa** [comment]
Yes, but for the channel table, when I try to add channel (Content sources) as admin or editor, I have an error in log file : Table database.channel doesn't exist. No channel are stored.

**Comment by mrmatthewgriffiths** [comment]
Hi,

Ok, can you please zip up your log file and sent it to me so I can review it more fully.

mg [ a t ] swiftly [ d o t ] org

Matt

**Comment by christiankakesa** [comment]
I send the log...
