### ISSUE TITLE
Log PEAR Extension

### ISSUE THREAD

**Issue by franwess** [ushahidi/Swiftriver-2011#47]
Hi guys

Trying to install Swiftriver but am battling with the server requirements. I have installed the PEAR Log module as required by Swiftriver but when the installer is checking the requirements it notifies that it is still requiring a Log.php file. 

The application is hosted on a Joyent Smartmachine running PHP 5.3 etc. The version of the Log module is 1.12.2 which is the newest version. I have also installed all the dependancies. Please help!

I am trying to install Batuque version of Swiftriver.

Kind regards

Francois Wessels

**Comment by christiankakesa** [comment]
Yep, your pear directory must be added in your php.ini at the "include_path" directive.
What's say "phpinfo();" about that ?

**Comment by mrmatthewgriffiths** [comment]
Hi Francois,

fenicks is quite right, you must make suer that PEAR Log is either on an included path or that you add the path to it.

Let us know how you get on.

Matt

**Comment by franwess** [comment]
Hi Matt

Thanks for the reply -- as explained to feniks as well for a non-programmer I am having difficulty knowing where exactly to do this. I understand that it is in the php.ini file but exactly what to add is the issue. I have tried a few suggestions from searches on google but none seem to work.

Would it be possible for you to just elaborate a bit more.

Kind regards

Francois Wessels

**Comment by mrmatthewgriffiths** [comment]
Hi Francois.

I believe that this article will explain how to make the changes to the php.ini file that are required:

http://www.php.net/manual/en/ini.core.php#ini.include-path

Regards,

Matt

**Comment by jgosier** [comment]
I'm going to mark this as closed as it's an environment configuration issue that we can't control.  However if you continue to have problems, we're happy to host an instance for you.

**Comment by franwess** [comment]
Hi there,

All in order -- would it be possible for you to host a test version for me whilst I continue to set up the environment?

Please let me know what I would have to do to get this up and running.

Kind regards

Francois Wessels

**Comment by jgosier** [comment]
Fran,

Please find the details to your very own instance of Sweeper App

url - 173.203.94.188
user / pass - admin / Uh96fP
