### ISSUE TITLE
Installation issue with Swiftriver Batuque

### ISSUE THREAD

**Issue by franwess** [ushahidi/Swiftriver-2011#48]
Hi Guys

I am trying to install Swiftriver but are hitting some walls with the server requirements -- 

I have installed the PEAR Log module (1.12.2) which is the latest version byt the Swiftriver installer still errors and requires a Log.php file. I have also installed all the dependencies for the PEAR Log module. 

Please help!

Kind regards

Francois Wessels

**Comment by christiankakesa** [comment]
(same as #47) Verify if your pear directory is mentionned in php.ini at the include_path directive.

**Comment by franwess** [comment]
@fenicks thanks very much for the help! for a non-programmer this is still quite difficult to master -- if not too much trouble could you possibly elaborate

Thanks again!

Francois

**Comment by christiankakesa** [comment]
I don't know if Batuque have the info.php script in his root directory.
If not, you can create it and put this line : <?php phpinfo(); ?>.
In web browser, go to the page http://your-instance-of-swiftriver/info.php.
Search the string "include_path" the value must contains some path, your Pear installation directory must appear.

If your Pear directory didn't appears, added itlike that : 
include_path = ".:/path_already_set:/my_pear_dir"

**Comment by franwess** [comment]
Hi fenicks

Thanks for the reply -- I have set the include path to the following but it still gives an error:

include_path =  ".:/opt/local/lib/php:/opt/local/lib/php/pear" 

## The error that I receive is the following

## Sorry, I can't access the PEAR Logging framework, I tried 'include_once("Log.php")' but it returned false. You need to ensure that the PEAR Logging system is installed and included

I do not know if this is correct though? I have in the meantime switched to the latest version of Swift to see if it will make a difference.

Kind regards

Francois

**Comment by christiankakesa** [comment]
Hi,
Ok, look at your pear directory you must have something like this : 

drwxrwxr-x Archive
drwxrwxr-x Console
drwxrwxr-x Log
-rw-rw-r--    Log.php
drwxrwxr-x OS
drwxrwxr-x PEAR
-rw-rw-r--    PEAR.php
-rw-rw-r--    PEAR5.php
drwxrwxr-x Structures
-rw-rw-r--    System.php
drwxrwxr-x XML
-rw-rw-r--    pearcmd.php
-rw-rw-r--    peclcmd.php

**Comment by franwess** [comment]
Hi fenicks

Thanks for all your help on this -- the strange thing is that the file you mention are located in .:/opt/local/lib/php and not in /opt/local/lib/php/pear . 

Is that not the problem that they should be located in the pear folder and not the php folder?

Kind regards

Fancois

**Comment by christiankakesa** [comment]
Not necessarily. It's not a good idea if your php installation directory is the same.

**Comment by franwess** [comment]
Hi there,

The files and folders you mention above in located inside .:/opt/local/lib/php -- should they be moved to be located inside /opt/local/lib/php/pear or what do you think is the solution to the error -- I am a bit stumped here so any help would be greatly appreciated.

KInd regards

Francois Wessels
