### ISSUE TITLE
allow "super approval" for admins

### ISSUE THREAD

**Issue by cbfrance** [ushahidi/Swiftriver-2011#49]
Smaller instances have a cold start problem -- if there are only two sweepers, they can not get the veracity score up more than 4.

**Comment by mrmatthewgriffiths** [comment]
Hi Chris, 

This is a very interesting bug. I will have to look into it.

Matt

**Comment by jgosier** [comment]
Related to this, there's no option for starting with a trusted source.

**Comment by jgosier** [comment]
@Chris we couldn't recreate that specific problem, two users (even one user) can drive the score up to 100, so long as there is a feed that sends you at least 50 items.

However, assuming you're dealing with individual content items, you can now start with a score of 100% a vote against it, so I'm going to mark this closed.

We're also considering a plugin where admins can assign a score, but this further off.
