### ISSUE TITLE
Installer shows blank page only on Chrome and Error 500 on Internet Explorer

### ISSUE THREAD

**Issue by gwerdi82** [ushahidi/Swiftriver-2011#50]
I tried to install swift but when I try to start Installation with http://www.mydomain.ch/swift/installer/ a blank page appears on google chrome. Same on Firefox and on Internet Explorer it gives me an error 500.

**Comment by gwerdi82** [comment]
my fault. php version was old. sorry

**Comment by jgosier** [comment]
Everything working now?  Let us know if you continue to have trouble.

**Comment by gwerdi82** [comment]
Installation was successful. Pear was missing on my server and I had some troubles to install. But now swift is installed but I cant do anything. The login button doesnt work. Just nothing happen. If you want to have a look: adrian-gwerder.ch/swift

**Comment by jgosier** [comment]
Okay, why don't we just host an instance for you.  email me jg [at] swiftly.org and I'll send over the details to the instance.

**Comment by gwerdi82** [comment]
thank you for offer but I don't need an extra instance. I installed swift only for testing and training to handle php scripts. I'll try around more or waiting for next release.
