### ISSUE TITLE
Sources and Turbine buttons don't work

### ISSUE THREAD

**Issue by dexteronomy** [ushahidi/Swiftriver-2011#53]
Add User and Logout work, but nothing happens when I click on Sources or either Turbine button.  I get this error if I look in the log. 
2010-11-07 14:20:38 --- ERROR: ErrorException [ 2048 ]: Creating default object from empty value ~ /Applications/XAMPP/xamppfiles/htdocs/swift/core/Workflows/ChannelServices/ChannelServicesBase.php [ 12 ]

**Comment by mrmatthewgriffiths** [comment]
Hi dexterinteractive,

Can you let me know which code build you have installed?

Thanks, Matt

**Comment by dexteronomy** [comment]
0.5.0 -  I tried the latest download from swiftly.org and github.. and they seem to be the same.  thanks!

**Comment by jgosier** [comment]
@dexter was this ever resolved for you?  Sounds like a javascript issue

**Comment by alefel** [comment]
This is the problem with PHP5 version.To resolve this problem install fire bug and when you click on these turbines it will show an error containing line number in the code in fire bug window. At that line remove '&' from there and then save it .Finally run swift river again.It solved my problem 

Hope it helps
cheers
siva

**Comment by jgosier** [comment]
alefel, thanks for this we'll kill this bug in the next release
