### ISSUE TITLE
Warning: Unexpected character in input: '\' (ASCII=92)

### ISSUE THREAD

**Issue by sirsly** [ushahidi/Swiftriver-2011#55]
Hi to all!
What can i do?
I've php 5.2.14

Silvio

**Comment by jgosier** [comment]
Is the version you're using pulled from the repo or was it a package?

**Comment by sirsly** [comment]
From here: http://swiftly.org/products-2/

**Comment by jgosier** [comment]
Okay, that's an old build.  Email me at jg[at]swiftly[dot]org and I'll send you the newer, unreleased package

**Comment by mangandini** [comment]
I got the same error with the v0.5.0 - Cape Jazz release =( I already sent you an email.

Thank you.

**Comment by alanreynosov** [comment]
Such error is because a PHP versión, i was in the same, so, i update PHP versión to 5.3 and fix it.

Best regards

**Comment by jgosier** [comment]
Swift v.0.5.0 is several months old. You should instead download Sweeper v.0.2.0 or later from http://github.com/ushahidi/Sweeper
