### ISSUE TITLE
swift.ushahidi.com/doc is down

### ISSUE THREAD

**Issue by evoltech** [ushahidi/Swiftriver-2011#56]
The documentation, as referenced in the README file, at http://swift.ushahidi.com/doc/ points to a un/misconfigured installation of DocuWiki

![Screen Shot](http://i332.photobucket.com/albums/m327/evoltech/swiftushahidicom-doc.png)

**Comment by jgosier** [comment]
Documentation is now located at wiki.ushahidi.com   the files you're referencing have been depreciated
