### ISSUE TITLE
Failed installation

### ISSUE THREAD

**Issue by gjs789** [ushahidi/Swiftriver-2011#59]
Hello

Admire the work you guys do. I have wanted to try swiftriver for some time. Today, I downloaded and installed swift-0.5.0 as per the instructions, on a desktop ubuntu to test it, with an aim to installing it on my ubuntu server in the future.

The Installer proceeded successfully, and i was redirected to the swiftriver main page. Nothing, however, other than the login button, or the create user button, works.

Only 1 table 'users' was created in the database.

I am running:
-Ubuntu 10.04 desktop
- Have a fresh install of LAMP, with PHP Version 5.3.2-1ubuntu4.7
- Pear is on path: ( .:/usr/share/php:/usr/share/pear  )

Does anyone know what has happened? How can I resolve this?

Best wishes
G

**Comment by jgosier** [comment]
I think you may just have a buggy build.  Please make sure to download Sweeper v0.3 (coming out later this week) or v0.2 from https://github.com/ushahidi/Sweeper

If you're still having trouble let us know but it sounds like a known javascript issue in that release.
