### ISSUE TITLE
installation problem in WAMP

### ISSUE THREAD

**Issue by olivewave** [ushahidi/Swiftriver-2011#60]
Hi

We are trying to setup swiftriver (Sweeper V0.3) to integrate with our ushahidi  deployment at  - http://www.olivewave.com/ushahidiind/ .
As my host does not support PHP 5.3 , I am trying to set up a swiftriver installation on local WAMP . However , I get stuck at the last step "Kohana Check".

Error : Let's ensure that the Kohana URL rewriter will work correctly.

Thats a shame, it seems that there are a few issues with the way that Kohana wants to do it's URLs. The best thing to do is check out this link and pay attention to the Troubleshooting #2 section. Its also worth noting that the Kohana framework runs best when run from a correctly configured virtual host in Apache. If this is all over your head, look here.

I have tried the solutions suggested at the links given but nothing works.

My .htaccess file :
# Turn on URL rewriting

RewriteEngine On
# Installation directory

RewriteBase /Sweeper_V0.3/web/ 
# Protect hidden files from being viewed

<Files .*>
    Order Deny,Allow
    Deny From All
</Files>
# Protect application and system files from being viewed

RewriteRule ^(?:application|modules|system)\b index.php/$0 [L]
# Allow any files or directories that exist to be displayed directly

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
# Rewrite all other URLs to index.php/URL

RewriteRule .\* index.php/$0 [PT]

extract from bootstrap.php :

//-- Configuration and initialization -----------------------------------------

/**
- Initialize Kohana, setting the default options.
  *
- The following options are available:
  *
- \- string   base_url    path, and optionally domain, of your application   NULL
- \- string   index_file  name of your index file, usually "index.php"       index.php
- \- string   charset     internal character set used for input and output   utf-8
- \- string   cache_dir   set the internal cache directory                   APPPATH/cache
- \- boolean  errors      enable or disable error handling                   TRUE
- \- boolean  profile     enable or disable internal profiling               TRUE
- - boolean  caching     enable or disable internal caching                 FALSE
    */
    Kohana::init(array(
    'base_url' => '/Sweeper_V0.3/web/', 
    ));
  
  My directory structure for swiftriver installation :  C:\wamp\www\Sweeper_V0.3\

can you please suggest a solution as installing swiftriver would really help us a lot infiltering and analyzing the  
data from our Ushahidi deployment .

Thanks in advance.
Olivewave Team

**Comment by ghost** [comment]
Could you please confirm that you have mod_rewrite enabled?

http://httpd.apache.org/docs/current/mod/mod_rewrite.html

This appears to be an issue with your setup, not SwiftRiver itself, so could we perhaps move this discussion to the mailing list? Am closing this issue on GitHub.

http://groups.google.com/group/swiftriver

**Comment by olivewave** [comment]
mod_rewrite was disabled on my apache  and after enabling Sweeper installed smoothly :).

Thanks a lot for looking into it.
Olivewave Team
http://www.olivewave.com/

**Comment by ghost** [comment]
Awesome, great to hear! Glad to have been of assistance. :)
